// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// A session token handed to the client to keep, for callers that have no
// cookie jar. A browser should never ask for one: script that can read a
// credential is script that can leak it.
type AccessToken struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
	User      *User     `json:"user"`
}

// A basket. Anonymous: it is identified by an unguessable token the client
// keeps, not by a signed-in user, because most shoppers never sign in.
//
// Names and prices are read from the catalogue every time this is resolved,
// never stored on the cart and never taken from the client.
type Cart struct {
	Token      string      `json:"token"`
	Currency   string      `json:"currency"`
	Items      []*CartItem `json:"items"`
	TotalCents int         `json:"totalCents"`
}

type CartItem struct {
	ProductID      string `json:"productId"`
	Name           string `json:"name"`
	UnitPriceCents int    `json:"unitPriceCents"`
	Quantity       int    `json:"quantity"`
	LineTotalCents int    `json:"lineTotalCents"`
}

type Checkout struct {
	// Where to send the shopper to pay.
	URL string `json:"url"`
}

type CreateProductInput struct {
	StoreID     string             `json:"storeId"`
	Name        string             `json:"name"`
	Description *string            `json:"description,omitempty"`
	PriceCents  int                `json:"priceCents"`
	Image       *ProductImageInput `json:"image,omitempty"`
}

type CreateStoreInput struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description,omitempty"`
}

type Mutation struct {
}

type Product struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	// Price in the smallest currency unit (cents). Integer on purpose: floating
	// point cannot represent 0.10 exactly, and the error compounds across a cart.
	// Clients format it for display.
	PriceCents int             `json:"priceCents"`
	Status     ProductStatus   `json:"status"`
	Images     []*ProductImage `json:"images"`
	CreatedAt  time.Time       `json:"createdAt"`
	UpdatedAt  time.Time       `json:"updatedAt"`
}

// Listing copy written from a product photograph.
type ProductCopy struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	// Describes the photograph itself, for screen readers and broken images.
	AltText string `json:"altText"`
}

type ProductImage struct {
	ID       string `json:"id"`
	URL      string `json:"url"`
	AltText  string `json:"altText"`
	Position int    `json:"position"`
}

// A photo to attach, identified by the storage key that POST /api/uploads
// returned. The key rather than a URL: the server builds the URL, so a client
// cannot point a product at an arbitrary address.
type ProductImageInput struct {
	Key     string  `json:"key"`
	AltText *string `json:"altText,omitempty"`
}

type Query struct {
}

type SetCartItemInput struct {
	StoreSlug string `json:"storeSlug"`
	ProductID string `json:"productId"`
	// Zero removes the line.
	Quantity int `json:"quantity"`
	// An existing cart token. Omit it to start a new cart.
	Token *string `json:"token,omitempty"`
}

type Store struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
	Currency    string    `json:"currency"`
	CreatedAt   time.Time `json:"createdAt"`
	// Products in this store. Omit `status` on a public storefront to get only ACTIVE ones.
	Products []*Product `json:"products"`
}

type UpdateProductInput struct {
	ID          string         `json:"id"`
	Name        *string        `json:"name,omitempty"`
	Description *string        `json:"description,omitempty"`
	PriceCents  *int           `json:"priceCents,omitempty"`
	Status      *ProductStatus `json:"status,omitempty"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
}

type ProductStatus string

const (
	ProductStatusDraft    ProductStatus = "DRAFT"
	ProductStatusActive   ProductStatus = "ACTIVE"
	ProductStatusArchived ProductStatus = "ARCHIVED"
)

var AllProductStatus = []ProductStatus{
	ProductStatusDraft,
	ProductStatusActive,
	ProductStatusArchived,
}

func (e ProductStatus) IsValid() bool {
	switch e {
	case ProductStatusDraft, ProductStatusActive, ProductStatusArchived:
		return true
	}
	return false
}

func (e ProductStatus) String() string {
	return string(e)
}

func (e *ProductStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductStatus", str)
	}
	return nil
}

func (e ProductStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
