package storage

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strings"
)

// Local stores files on the filesystem. It exists so the project runs with no
// cloud account: clone, set DATABASE_URL, and uploads work.
type Local struct {
	dir     string
	urlPath string // public path prefix, e.g. "/uploads"
}

func NewLocal(dir, urlPath string) (*Local, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("create upload directory: %w", err)
	}
	return &Local{dir: dir, urlPath: strings.TrimSuffix(urlPath, "/")}, nil
}

func (l *Local) Put(_ context.Context, contentType string, r io.Reader) (Object, error) {
	key, err := NewKey(contentType)
	if err != nil {
		return Object{}, err
	}

	// Write to a temporary file and rename into place. A crash mid-write then
	// leaves no half-written file that later reads would treat as valid.
	tmp, err := os.CreateTemp(l.dir, ".partial-*")
	if err != nil {
		return Object{}, fmt.Errorf("create temp file: %w", err)
	}
	defer os.Remove(tmp.Name()) // no-op once the rename below succeeds

	size, err := io.Copy(tmp, r)
	if err != nil {
		tmp.Close()
		return Object{}, fmt.Errorf("write upload: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return Object{}, fmt.Errorf("close upload: %w", err)
	}

	if err := os.Rename(tmp.Name(), filepath.Join(l.dir, key)); err != nil {
		return Object{}, fmt.Errorf("store upload: %w", err)
	}

	return Object{
		Key:         key,
		URL:         l.urlPath + "/" + key,
		ContentType: contentType,
		Size:        size,
	}, nil
}

func (l *Local) Open(_ context.Context, key string) (io.ReadCloser, string, error) {
	// Keys are generated by NewKey, but this method takes whatever the caller
	// passes, so treat the key as untrusted: strip any directory part before
	// it can walk out of the upload directory.
	safe := filepath.Base(path.Clean("/" + key))
	if safe == "." || safe == string(filepath.Separator) || safe == "/" {
		// An empty or all-separator key collapses to the directory itself.
		return nil, "", ErrNotFound
	}

	f, err := os.Open(filepath.Join(l.dir, safe))
	if errors.Is(err, os.ErrNotExist) {
		return nil, "", ErrNotFound
	}
	if err != nil {
		return nil, "", fmt.Errorf("open object: %w", err)
	}

	// Opening a directory succeeds on most systems and only fails on read,
	// which surfaces far away from the cause.
	info, err := f.Stat()
	if err != nil || !info.Mode().IsRegular() {
		f.Close()
		return nil, "", ErrNotFound
	}

	contentType := "application/octet-stream"
	if t, ok := extensionTypes[strings.ToLower(filepath.Ext(safe))]; ok {
		contentType = t
	}
	return f, contentType, nil
}

// Handler serves the stored files. Only used by the local driver: with GCS the
// bucket serves them directly.
func (l *Local) Handler() http.Handler {
	fs := http.FileServer(http.Dir(l.dir))
	return http.StripPrefix(l.urlPath+"/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Uploads are content-addressed by a random key, so they never change
		// and can be cached hard.
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		// Belt and braces: even though only image types are ever stored, tell
		// the browser not to second-guess the declared type.
		w.Header().Set("X-Content-Type-Options", "nosniff")
		fs.ServeHTTP(w, r)
	}))
}

var extensionTypes = map[string]string{
	".jpg":  "image/jpeg",
	".png":  "image/png",
	".webp": "image/webp",
	".gif":  "image/gif",
}
